### ISSUE TITLE
Not able to configure data source in Grafana Cloud (Grafana v11.1.0-69051 (9d44c8e8cf))

### ISSUE THREAD

**Issue by 0x01F4** [oracle/oci-grafana-logs#117] opened 2024-04-11 16:11 UTC
Grafana Cloud version: v11.1.0-69051 (9d44c8e8cf)
oci-logs-datasource version: 4.0.2

When trying to configure the datasource below error occurs in UI.oci-metrics-datasource is working in same Grafana version

`An unexpected error happened
TypeError: Attempted to assign to readonly property.

F@
div
vt@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/Connections.5ec3a2949b5ef0cf667d.js:48:2353
o@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/9602.ccb8f3676ec5906e3096.js:1:192
form
Pt@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/Connections.5ec3a2949b5ef0cf667d.js:56:1928
At@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/Connections.5ec3a2949b5ef0cf667d.js:56:1481
d@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/9602.ccb8f3676ec5906e3096.js:370:18134
div
div
div
div
X@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/885.0dcda3e8870234b9d9f5.js:903:4472
c@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/9602.ccb8f3676ec5906e3096.js:194:29736
u
div
V@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/9602.ccb8f3676ec5906e3096.js:370:21864
wt@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/Connections.5ec3a2949b5ef0cf667d.js:56:5002
Bt@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/Connections.5ec3a2949b5ef0cf667d.js:56:5352
K@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/885.0dcda3e8870234b9d9f5.js:1048:29160
K@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/885.0dcda3e8870234b9d9f5.js:1048:31337
Gt@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/Connections.5ec3a2949b5ef0cf667d.js:64:2099
Suspense
l@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/9602.ccb8f3676ec5906e3096.js:194:124027
mo@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/9602.ccb8f3676ec5906e3096.js:315:10982
K@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/885.0dcda3e8870234b9d9f5.js:1048:29160
or@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/885.0dcda3e8870234b9d9f5.js:1039:4480
ls@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/885.0dcda3e8870234b9d9f5.js:1039:12025
kt@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/885.0dcda3e8870234b9d9f5.js:1048:17411
K@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/885.0dcda3e8870234b9d9f5.js:1048:31337
main
div
div
div
Ts@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/9602.ccb8f3676ec5906e3096.js:315:2467
div
Kr@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/9602.ccb8f3676ec5906e3096.js:315:6888
or@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/885.0dcda3e8870234b9d9f5.js:1039:4480
ls@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/885.0dcda3e8870234b9d9f5.js:1039:12025
as@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/885.0dcda3e8870234b9d9f5.js:1039:11388
pr@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/885.0dcda3e8870234b9d9f5.js:1048:17696
K@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/885.0dcda3e8870234b9d9f5.js:1048:25376
g@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/885.0dcda3e8870234b9d9f5.js:112:8958
v@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/885.0dcda3e8870234b9d9f5.js:1383:97064
u@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/9602.ccb8f3676ec5906e3096.js:610:21215
l@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/9602.ccb8f3676ec5906e3096.js:194:124027
f@
ot@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/885.0dcda3e8870234b9d9f5.js:1020:532
$i@https://grafana-assets.grafana.net/grafana/11.1.0-69051/public/build/9602.ccb8f3676ec5906e3096.js:326:132`

**Comment by mamorett** [comment] 2024-09-06 07:35
Version 5.0.0 now supports Grafana11

**Comment by Phil57** [comment] 2024-09-20 08:39
This doesn't seem to fix it for me

`An unexpected error happened
Details
TypeError: Cannot assign to read only property 'profile0' of object '[object Object]'

    at V (https://xxxxx.grafana.net/public/plugins/oci-logs-datasource/module.js?_cache=5.0.0:2:8167)
    at div
    at Ds (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/Connections.7281e15e849c49f5833b.js:48:2374)
    at o (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/1180.a1da278974184b635bb5.js:1:183)
    at form
    at Ls (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/Connections.7281e15e849c49f5833b.js:48:5837)
    at Is (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/Connections.7281e15e849c49f5833b.js:48:5394)
    at a (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/1180.a1da278974184b635bb5.js:205:17339)
    at div
    at div
    at h (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/1180.a1da278974184b635bb5.js:170:2036)
    at div
    at F (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/1180.a1da278974184b635bb5.js:205:21257)
    at Us (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/Connections.7281e15e849c49f5833b.js:48:8771)
    at ws (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/Connections.7281e15e849c49f5833b.js:48:9167)
    at je (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/7639.c24f5a5a1fe43e49c3d2.js:317:25343)
    at je (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/7639.c24f5a5a1fe43e49c3d2.js:317:27534)
    at qs (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/Connections.7281e15e849c49f5833b.js:56:2222)
    at Suspense
    at h (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/1180.a1da278974184b635bb5.js:12:134183)
    at ae (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/1180.a1da278974184b635bb5.js:159:7133)
    at je (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/7639.c24f5a5a1fe43e49c3d2.js:317:25343)
    at ve (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/7639.c24f5a5a1fe43e49c3d2.js:317:4578)
    at We (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/7639.c24f5a5a1fe43e49c3d2.js:317:12253)
    at tr (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/7639.c24f5a5a1fe43e49c3d2.js:308:18051)
    at je (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/7639.c24f5a5a1fe43e49c3d2.js:317:27534)
    at div
    at https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/3719.5a4f40f493866b9b64b2.js:1:134086
    at main
    at div
    at div
    at div
    at lo (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/1180.a1da278974184b635bb5.js:161:2401)
    at yi (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/1180.a1da278974184b635bb5.js:161:7883)
    at ve (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/7639.c24f5a5a1fe43e49c3d2.js:317:4578)
    at We (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/7639.c24f5a5a1fe43e49c3d2.js:317:12253)
    at Le (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/7639.c24f5a5a1fe43e49c3d2.js:317:11583)
    at gr (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/7639.c24f5a5a1fe43e49c3d2.js:308:18353)
    at P (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/1180.a1da278974184b635bb5.js:5:186772)
    at je (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/7639.c24f5a5a1fe43e49c3d2.js:317:21506)
    at Ei (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/1180.a1da278974184b635bb5.js:161:9318)
    at div
    at d (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/1180.a1da278974184b635bb5.js:1944:26584)
    at p (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/7639.c24f5a5a1fe43e49c3d2.js:152:9137)
    at C (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/4239.a47a62e15d81a0718c37.js:186:17460)
    at i (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/3719.5a4f40f493866b9b64b2.js:24:11903)
    at h (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/1180.a1da278974184b635bb5.js:12:134183)
    at l (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/1180.a1da278974184b635bb5.js:12:134692)
    at Jn (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/4239.a47a62e15d81a0718c37.js:190:507)
    at Fo (https://grafana-assets.grafana.net/grafana/11.3.0-75826/public/build/1180.a1da278974184b635bb5.js:161:11005)`

**Comment by mamorett** [comment] 2024-11-04 09:22
I could not reproduce yet your issue. However I will reopen it and I will have a look.

**Comment by mamorett** [comment] 2024-11-06 09:09
Hi. I just created a new datasource in Grafana Cloud using OCI Logs plugin 5.2 and it works without any problem 
![image](https://github.com/user-attachments/assets/85b5a377-57a6-46d7-8e5c-f68bf3191f82)
Can you try to reconfigure the datasource from scraatch ? Maybe you got some issue in your datasource.

**Comment by bscarbrough** [comment] 2024-11-08 14:00
Same here, still having the same issue. I even uninstalled and reinstalled with the same results.

**Comment by bscarbrough** [comment] 2024-11-18 15:40
@mamorett, has there been an update on this issue?

**Comment by mamorett** [comment] 2024-11-20 14:27
We are investigating. So far we were not able to reproduce the issue, which is quite weird. But we are digging into it.

**Comment by jvinaya** [comment] 2024-11-20 15:52
Here’s the latest update: We were able to reproduce the issue in Grafana Cloud. A follow-up story has been added to our backlog to address this. We will provide updates here as we make progress toward a fix.

**Comment by jvinaya** [comment] 2024-11-27 12:46
Hi @bscarbrough and @Phil57,

We have released a new version of the logs plugin (v5.0.2). Could you please update to this latest version, test the datasource creation, and let us know if it works as expected?
Thanks in advance

**Comment by Phil57** [comment] 2024-11-27 13:54
The form is now working. I have some issues when testing and saving but I must have something wrong in the config somewhere.

`ListLogGroupsRequest failed in each Compartments in profile Error returned by LogSearch Service. Http Status Code: 404. Error Code: NotAuthorizedOrNotFound. `

Thanks !

**Comment by bscarbrough** [comment] 2024-11-27 14:33
Seeing the same thing as @Phil57. Have the policy/permission requirements changed any?

**Comment by jvinaya** [comment] 2024-11-27 14:42
No, there haven’t been any changes to the policy/permission requirements.

**Comment by Phil57** [comment] 2024-11-27 14:56
`Allow group 'Default'/'Grafana' to read metrics in tenancy`
`Allow group 'Default'/'Grafana' to read compartments in tenancy`
`Allow group 'Default'/'Grafana' to read log-groups in tenancy`
`Allow group 'Default'/'Grafana' to read log-content in tenancy`

My config is that and the metrics part is working fine.
I spun up a local docker Grafana and issue is the same, so not relace to the Cloud instance

**Comment by mamorett** [comment] 2024-11-27 15:29
Hi. I think this is missing:
allow group Grafana to read audit-events in tenancy

**Comment by Phil57** [comment] 2024-11-27 15:31
@mamorett 
Thanks, that did the trick.
The doc needs un update then :)

**Comment by mamorett** [comment] 2024-11-27 15:51
Yeah, it is already there :) Was a PR pushed some times ago but yeah not originally there indeed. 
![image](https://github.com/user-attachments/assets/70070efb-a06a-484e-aead-f78337b112d9)

**Closed** 2024-11-28 08:56 UTC
